### ISSUE TITLE
Score

### ISSUE THREAD

**Issue by mzl-agh** [tomeroth/RabbitMQ#1]
Right now it's 2 points, however if solution with proper chat will be here, we can discuss :)

BR,
M.Z.Ł.

**Comment by tomeroth** [comment]
I have managed to create proper solution with chat. Thank you giving me more time.

**Comment by mzl-agh** [comment]
Unfortunately, this task is still not done. The main purpose was making one application which is publisher and subscriber at the same time (so executing 3 or 4 instances of this application will create chat). It may be done with merging publisher/subscriber code and using randomly generated ID's, which are used in RabbitHutch subscription.
